# Generated by Django 3.2.3 on 2021-05-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Действуещее законадательство'), (2, 'Проекты'), (3, 'Проекты_1'), (4, 'Проекты_2')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('image', models.FileField(upload_to='image')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Действуещее законадательство'), (2, 'Проекты'), (3, 'Проекты_1'), (4, 'Проекты_2')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributer.news')),
            ],
        ),
    ]
