# Generated by Django 3.2.3 on 2021-06-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributer', '0002_auto_20210603_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
